// js/jobs.js - Realistic dataset of 20+ live jobs across Private & Government sectors

const JOBS_DATA = [
    {
        id: "job-1",
        title: "AI & Machine Learning Engineer",
        organization: "NexusTech AI Labs",
        sector: "Private",
        location: "Bengaluru, India",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$120,000 - $150,000 / yr",
        postedDate: "2026-08-10",
        deadline: "2026-08-30",
        requiredSkills: ["Python", "Machine Learning", "SQL", "Data Analysis", "C++"],
        interests: ["Artificial Intelligence", "Machine Learning", "Data Science", "Software Development"],
        description: "Design, build, and deploy production-level machine learning models, neural networks, and scalable data pipelines for enterprise solutions.",
        applyUrl: "https://www.linkedin.com/jobs/search/?keywords=AI%20Machine%20Learning%20Engineer",
        nextSkillsToLearn: ["TensorFlow", "PyTorch", "MLOps", "Deep Learning"]
    },
    {
        id: "job-2",
        title: "Full Stack Web Developer",
        organization: "CloudScale Software",
        sector: "Private",
        location: "Remote / San Francisco, CA",
        workType: "Remote",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$110,000 - $135,000 / yr",
        postedDate: "2026-08-11",
        deadline: "2026-09-05",
        requiredSkills: ["JavaScript", "HTML", "CSS", "React", "Node.js", "SQL", "Git/GitHub"],
        interests: ["Web Development", "Software Development", "UI/UX Design", "Database Management"],
        description: "Develop responsive, modern web applications from frontend interfaces to scalable backend microservices and database structures.",
        applyUrl: "https://www.indeed.com/jobs?q=Full+Stack+Developer",
        nextSkillsToLearn: ["AWS", "Docker", "TypeScript", "GraphQL"]
    },
    {
        id: "job-3",
        title: "Cybersecurity Analyst (Public Sector)",
        organization: "National Cyber Security Center",
        sector: "Government",
        location: "Washington, D.C. / New Delhi",
        workType: "On-site",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$95,000 - $115,000 / yr",
        postedDate: "2026-08-08",
        deadline: "2026-08-25",
        requiredSkills: ["Cybersecurity", "Networking", "Python", "Problem Solving", "SQL"],
        interests: ["Cybersecurity", "Networking", "Government Services", "Data Science"],
        description: "Protect critical government infrastructure, monitor security breaches, audit systems, and execute vulnerability threat assessments.",
        applyUrl: "https://www.usajobs.gov/Search/Results?k=Cybersecurity",
        nextSkillsToLearn: ["Ethical Hacking", "SIEM Tools", "Cloud Security", "CISSP"]
    },
    {
        id: "job-4",
        title: "Cloud Solutions Architect",
        organization: "Apex Enterprise Cloud",
        sector: "Private",
        location: "Austin, TX",
        workType: "Remote",
        jobCategory: "Full-time",
        experience: "Advanced",
        salary: "$140,000 - $175,000 / yr",
        postedDate: "2026-08-12",
        deadline: "2026-09-12",
        requiredSkills: ["AWS", "Azure", "Docker", "Kubernetes", "DevOps", "Networking", "Python"],
        interests: ["Cloud Computing", "DevOps", "Networking", "Software Development"],
        description: "Architect secure multi-cloud environments, manage container orchestration, and lead infrastructure automated deployment.",
        applyUrl: "https://www.wellfound.com/jobs?q=Cloud+Architect",
        nextSkillsToLearn: ["Terraform", "Serverless Architecture", "Cost Optimization"]
    },
    {
        id: "job-5",
        title: "Junior Data Analyst",
        organization: "Insight Analytics Corp",
        sector: "Private",
        location: "Chicago, IL",
        workType: "Hybrid",
        jobCategory: "Fresher",
        experience: "Beginner",
        salary: "Salary not disclosed",
        postedDate: "2026-08-09",
        deadline: "2026-08-28",
        requiredSkills: ["SQL", "Python", "Data Analysis", "HTML", "CSS", "Problem Solving"],
        interests: ["Data Science", "Database Management", "Finance", "Research"],
        description: "Transform complex data into actionable business intelligence dashboards, statistical metrics, and executive reports.",
        applyUrl: "https://www.linkedin.com/jobs/search/?keywords=Junior%20Data%20Analyst",
        nextSkillsToLearn: ["PowerBI", "Tableau", "R", "Advanced SQL"]
    },
    {
        id: "job-6",
        title: "National IT Officer (NIC)",
        organization: "National Informatics Centre (Govt)",
        sector: "Government",
        location: "Multiple Locations, India",
        workType: "On-site",
        jobCategory: "Full-time",
        experience: "Beginner",
        salary: "₹70,000 - ₹95,000 / mo",
        postedDate: "2026-08-05",
        deadline: "2026-08-22",
        requiredSkills: ["C", "C++", "Java", "SQL", "Networking", "Communication"],
        interests: ["Government Services", "Software Development", "Database Management", "Networking"],
        description: "Manage e-governance technology deployments, maintain secure public databases, and develop government digital services.",
        applyUrl: "https://www.nic.in/vacancies",
        nextSkillsToLearn: ["System Administration", "Web Security", "Linux Systems"]
    },
    {
        id: "job-7",
        title: "UI/UX Product Designer",
        organization: "Aura Creative Studio",
        sector: "Private",
        location: "New York, NY",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$90,000 - $115,000 / yr",
        postedDate: "2026-08-07",
        deadline: "2026-08-29",
        requiredSkills: ["HTML", "CSS", "JavaScript", "Communication", "Problem Solving"],
        interests: ["UI/UX Design", "Web Development", "Digital Marketing"],
        description: "Craft visually compelling visual designs, interactive wireframes, component design systems, and user testing workflows.",
        applyUrl: "https://dribbble.com/jobs",
        nextSkillsToLearn: ["Figma Mastery", "User Research", "Prototyping", "Design Systems"]
    },
    {
        id: "job-8",
        title: "DevOps Engineer",
        organization: "Streamline DevOps Inc",
        sector: "Private",
        location: "Seattle, WA",
        workType: "Remote",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$125,000 - $145,000 / yr",
        postedDate: "2026-08-11",
        deadline: "2026-09-02",
        requiredSkills: ["Git/GitHub", "Docker", "Kubernetes", "AWS", "DevOps", "Python", "Networking"],
        interests: ["DevOps", "Cloud Computing", "Networking", "Software Development"],
        description: "Automate CI/CD continuous delivery pipelines, infrastructure as code, server monitoring, and system uptime optimization.",
        applyUrl: "https://www.glassdoor.com/Job/devops-engineer-jobs-SRCH_KO0,15.htm",
        nextSkillsToLearn: ["Ansible", "Prometheus", "Grafana", "GitLab CI"]
    },
    {
        id: "job-9",
        title: "Mobile App Specialist (iOS / Android)",
        organization: "Veloce Mobility Labs",
        sector: "Private",
        location: "London, UK",
        workType: "Remote",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "£65,000 - £80,000 / yr",
        postedDate: "2026-08-06",
        deadline: "2026-08-26",
        requiredSkills: ["Java", "JavaScript", "React", "Git/GitHub", "Problem Solving"],
        interests: ["Mobile Development", "Software Development", "UI/UX Design"],
        description: "Build high-performance native and cross-platform mobile apps with fluid animations, push notifications, and offline caching.",
        applyUrl: "https://www.indeed.com/jobs?q=Mobile+App+Developer",
        nextSkillsToLearn: ["Flutter", "React Native", "Swift", "Kotlin"]
    },
    {
        id: "job-10",
        title: "Database Administrator & Security Specialist",
        organization: "Federal Reserve Technology Division",
        sector: "Government",
        location: "Washington, D.C.",
        workType: "On-site",
        jobCategory: "Full-time",
        experience: "Advanced",
        salary: "$130,000 - $160,000 / yr",
        postedDate: "2026-08-03",
        deadline: "2026-08-24",
        requiredSkills: ["SQL", "Database Management", "Cybersecurity", "Leadership", "C++"],
        interests: ["Database Management", "Government Services", "Cybersecurity", "Finance"],
        description: "Ensure 99.999% database uptime, high-speed query indexing, strict public sector compliance, and encryption at rest.",
        applyUrl: "https://www.usajobs.gov/Search/Results?k=Database+Administrator",
        nextSkillsToLearn: ["PostgreSQL Tuning", "NoSQL Databases", "Disaster Recovery"]
    },
    {
        id: "job-11",
        title: "Digital Growth & Marketing Strategist",
        organization: "OmniGrowth Media",
        sector: "Private",
        location: "Los Angeles, CA",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Beginner",
        salary: "Salary not disclosed",
        postedDate: "2026-08-09",
        deadline: "2026-08-31",
        requiredSkills: ["Communication", "Data Analysis", "HTML", "CSS", "Problem Solving"],
        interests: ["Digital Marketing", "Management", "Finance", "UI/UX Design"],
        description: "Drive multi-channel user acquisition campaigns, SEO performance optimization, analytics tracking, and social strategies.",
        applyUrl: "https://www.linkedin.com/jobs/search/?keywords=Digital%20Marketing%20Strategist",
        nextSkillsToLearn: ["Google Analytics 4", "SEO Auditing", "Meta Ads Manager", "Copywriting"]
    },
    {
        id: "job-12",
        title: "Backend Software Engineer",
        organization: "HyperScale Core Systems",
        sector: "Private",
        location: "Toronto, Canada",
        workType: "Remote",
        jobCategory: "Full-time",
        experience: "Advanced",
        salary: "$135,000 - $165,000 / yr",
        postedDate: "2026-08-10",
        deadline: "2026-09-08",
        requiredSkills: ["Java", "Python", "C++", "SQL", "Node.js", "AWS", "Git/GitHub"],
        interests: ["Software Development", "Database Management", "Cloud Computing"],
        description: "Build ultra-low latency backend APIs, distributed microservice architectures, transaction queues, and scalable caching.",
        applyUrl: "https://www.wellfound.com/jobs?q=Backend+Engineer",
        nextSkillsToLearn: ["Go (Golang)", "Kafka", "Redis", "Microservices Design"]
    },
    {
        id: "job-13",
        title: "Public Health Data Scientist",
        organization: "Department of Health & Human Services",
        sector: "Government",
        location: "Atlanta, GA",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$105,000 - $125,000 / yr",
        postedDate: "2026-08-04",
        deadline: "2026-08-27",
        requiredSkills: ["Python", "Machine Learning", "Data Analysis", "SQL", "Problem Solving"],
        interests: ["Government Services", "Data Science", "Research", "Artificial Intelligence"],
        description: "Analyze epidemiology datasets, predictive population health forecasting models, and government statistical surveys.",
        applyUrl: "https://www.usajobs.gov/Search/Results?k=Data+Scientist",
        nextSkillsToLearn: ["Biostatistics", "Spatial Data Analysis", "SAS / SPSS"]
    },
    {
        id: "job-14",
        title: "IT Project & Operations Manager",
        organization: "Global Enterprise Solutions",
        sector: "Private",
        location: "Boston, MA",
        workType: "On-site",
        jobCategory: "Full-time",
        experience: "Expert",
        salary: "$145,000 - $180,000 / yr",
        postedDate: "2026-08-02",
        deadline: "2026-08-22",
        requiredSkills: ["Leadership", "Communication", "Problem Solving", "Git/GitHub"],
        interests: ["Management", "Government Services", "Finance"],
        description: "Oversee agile sprint teams, manage multi-million dollar software deliverables, mitigate client risks, and foster leadership.",
        applyUrl: "https://www.indeed.com/jobs?q=IT+Project+Manager",
        nextSkillsToLearn: ["Agile/Scrum (PMP)", "Jira Enterprise", "Risk Management"]
    },
    {
        id: "job-15",
        title: "AI Research Scientist",
        organization: "DeepVision Research Labs",
        sector: "Private",
        location: "Palo Alto, CA",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Expert",
        salary: "$160,000 - $210,000 / yr",
        postedDate: "2026-08-11",
        deadline: "2026-09-15",
        requiredSkills: ["Python", "Machine Learning", "C++", "Data Analysis", "Problem Solving"],
        interests: ["Artificial Intelligence", "Machine Learning", "Research", "Data Science"],
        description: "Conduct cutting-edge computer vision research, publish foundational AI papers, and train large language models (LLMs).",
        applyUrl: "https://www.linkedin.com/jobs/search/?keywords=AI%20Research%20Scientist",
        nextSkillsToLearn: ["LLM Fine-Tuning", "CUDA Programming", "Transformer Architectures"]
    },
    {
        id: "job-16",
        title: "Frontend Engineering Intern",
        organization: "Vercel Ecosystem Fellows",
        sector: "Private",
        location: "Remote",
        workType: "Remote",
        jobCategory: "Internship",
        experience: "Beginner",
        salary: "$30 - $40 / hr (Stipend)",
        postedDate: "2026-08-12",
        deadline: "2026-09-01",
        requiredSkills: ["HTML", "CSS", "JavaScript", "React", "Git/GitHub"],
        interests: ["Web Development", "UI/UX Design", "Software Development"],
        description: "Build modern web user interfaces, component design systems, and web performance micro-optimizations under senior mentorship.",
        applyUrl: "https://www.wellfound.com/jobs?q=Frontend+Intern",
        nextSkillsToLearn: ["Next.js", "TypeScript", "TailwindCSS"]
    },
    {
        id: "job-17",
        title: "Cyber Defence Graduate Trainee",
        organization: "Ministry of Defence IT Directorate",
        sector: "Government",
        location: "London, UK / New Delhi",
        workType: "On-site",
        jobCategory: "Fresher",
        experience: "Beginner",
        salary: "£35,000 / yr",
        postedDate: "2026-08-08",
        deadline: "2026-08-29",
        requiredSkills: ["Cybersecurity", "Networking", "C", "C++", "Problem Solving"],
        interests: ["Cybersecurity", "Government Services", "Networking"],
        description: "Entry-level public sector graduate program focusing on cyber defense, network threat monitoring, and infrastructure hardening.",
        applyUrl: "https://www.usajobs.gov/Search/Results?k=Cyber",
        nextSkillsToLearn: ["Network Forensics", "Cryptography", "Linux Admin"]
    },
    {
        id: "job-18",
        title: "Data Engineering Associate",
        organization: "DataPulse Pipeline Systems",
        sector: "Private",
        location: "Denver, CO",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "$100,000 - $120,000 / yr",
        postedDate: "2026-08-07",
        deadline: "2026-08-30",
        requiredSkills: ["Python", "SQL", "Database Management", "AWS", "Git/GitHub"],
        interests: ["Data Science", "Database Management", "Cloud Computing"],
        description: "Construct automated ETL data pipelines, manage data warehousing architectures, and ensure real-time streaming data quality.",
        applyUrl: "https://www.linkedin.com/jobs/search/?keywords=Data%20Engineer",
        nextSkillsToLearn: ["Apache Spark", "Snowflake", "dbt", "Airflow"]
    },
    {
        id: "job-19",
        title: "Systems Software Engineer (C++)",
        organization: "QuantumCore Operating Systems",
        sector: "Private",
        location: "San Jose, CA",
        workType: "On-site",
        jobCategory: "Full-time",
        experience: "Advanced",
        salary: "$150,000 - $185,000 / yr",
        postedDate: "2026-08-09",
        deadline: "2026-09-04",
        requiredSkills: ["C++", "C", "Networking", "Problem Solving", "Git/GitHub"],
        interests: ["Software Development", "Networking", "Research"],
        description: "Develop low-level kernel drivers, embedded system firmware, memory allocators, and real-time execution engines.",
        applyUrl: "https://www.indeed.com/jobs?q=C%2B%2B+Systems+Engineer",
        nextSkillsToLearn: ["Rust", "Assembly Language", "POSIX Threads"]
    },
    {
        id: "job-20",
        title: "Public E-Governance Solutions Developer",
        organization: "Digital India Technology Mission",
        sector: "Government",
        location: "New Delhi, India",
        workType: "Hybrid",
        jobCategory: "Full-time",
        experience: "Intermediate",
        salary: "₹85,000 - ₹1,10,000 / mo",
        postedDate: "2026-08-10",
        deadline: "2026-09-02",
        requiredSkills: ["Java", "SQL", "HTML", "CSS", "JavaScript", "Database Management"],
        interests: ["Government Services", "Software Development", "Web Development"],
        description: "Build secure public portals, mobile e-governance apps, and citizens' digital identity verification systems.",
        applyUrl: "https://internship.aicte-india.org/",
        nextSkillsToLearn: ["Spring Boot", "Microservices", "API Gateways"]
    }
];
